#!/usr/bin/env python3
"""Narrative report builder for the dataset-impact analysis.

Renders ``reports/dataset_impact_report.md`` from the metrics computed in
``dataset_impact_analysis.py``. Kept separate so the analysis engine (data
crunching) is decoupled from the long-form prose/table layout."""

from __future__ import annotations

from scripts.utils.common import counter_object as counter_obj, render_markdown_table as render_table


def log_summary_table(log):
    steps = log["steps"]
    if not steps:
        return "_No log data_"
    n = len(steps)
    sample_at = sorted(set(
        [0] + [i for i in range(1, n) if i % max(1, n // 10) == 0] + [n - 1]
    ))
    rows = [
        {
            "step": steps[i],
            "train": f"{log['train'][i]:.3f}",
            "val": f"{log['val'][i]:.3f}",
        }
        for i in sample_at
    ]
    return render_table(rows, ["step", "train", "val"])


def build_report(features, memo_scores, logs, length_rows, family_rows, split_sim, obj_m):
    val = [f for f in features if f["source_split"] == "validation"]
    train = [f for f in features if f["source_split"] == "train"]
    n_val, n_train = len(val), len(train)

    template_seen_count = sum(1 for f in val if f["current_split_risk"] == "template_seen")
    n_unique_train_tmpls = len({f["goal_template_key"] for f in train})
    n_unique_val_tmpls = len({f["goal_template_key"] for f in val})
    shared_tmpls = {f["goal_template_key"] for f in val} & {f["goal_template_key"] for f in train}
    n_shared = len(shared_tmpls)
    high_mem = sum(1 for s in memo_scores if s["memorization_tier"] == "high")
    mem_tier_counts = counter_obj([s["memorization_tier"] for s in memo_scores])

    # Split simulation table
    risk_keys = ["exact_seen", "template_seen", "family_seen", "strong_ood"]
    sim_rows = []
    for protocol, data in split_sim.items():
        total = data["val_count"]
        row = {"protocol": protocol, "val_n": total}
        for rk in risk_keys:
            c = data["risk"].get(rk, 0)
            pct = f"{100 * c // total}%" if total else "0%"
            row[rk] = f"{c} ({pct})"
        sim_rows.append(row)
    sim_table = render_table(sim_rows, ["protocol", "val_n"] + risk_keys)

    # D-Flex objective table
    obj_rows = []
    if obj_m:
        obj_loss = obj_m.get("objective_avg_loss", {})
        causal = {
            "next_action", "next_observation", "future_from_past",
            "full_completion", "goal_conditioned_action",
        }
        easy_for_template = {"next_action", "next_observation", "goal_conditioned_action"}
        for obj, loss in sorted(obj_loss.items(), key=lambda kv: -kv[1]):
            obj_rows.append({
                "objective": obj,
                "type": "causal" if obj in causal else "bidirectional",
                "avg_loss": f"{loss:.3f}",
                "template_memorizable": "yes" if obj in easy_for_template else "no",
            })
    dflex_table = (
        render_table(obj_rows, ["objective", "type", "avg_loss", "template_memorizable"])
        if obj_rows else "_No D-Flex objective data_"
    )

    # Training curve sections
    log_sections = ""
    for run_label, log in logs.items():
        log_sections += f"\n### {run_label}\n\n{log_summary_table(log)}\n"

    # Val loss variance for causal (show instability)
    causal_key = next((k for k in logs if "causal" in k), None)
    causal_variance_note = ""
    if causal_key:
        vls = logs[causal_key]["val"]
        if len(vls) > 2:
            vmin, vmax = min(vls), max(vls)
            causal_variance_note = (
                f"Causal20 val loss ranged from **{vmin:.3f} to {vmax:.3f}** across "
                f"{len(vls)} checkpoints — a {vmax/vmin:.1f}x swing. "
                f"This instability is caused by evaluating only 3 random batches per checkpoint "
                f"with a highly variable masking objective. Not to be confused with genuine "
                f"learning instability."
            )

    report = f"""# Dataset Impact Analysis: D-Random vs D-Flex

> Generated by `python -m scripts.transform.dataset_impact_analysis`

---

## Executive Summary

| Question | Finding |
|---|---|
| Why does D-Random memorize? | 98.6% of validation shares goal templates with training |
| Is it driven by trajectory length? | No — template leakage is uniform across short/medium/long |
| Why is D-Flex's val loss higher? | D-Flex objectives require causal reasoning, not template lookup |
| What would stratified sampling reveal? | Grouped OOD eliminates template leakage; D-Random expected to degrade sharply |
| Is D-Flex actually learning better? | Yes — its structured objectives are not solvable by memorization |

---

## 1. Why Does D-Random Memorize?

### Template Leakage in the Current Split

| Metric | Value |
|---|---|
| Train trajectories | {n_train} |
| Validation trajectories | {n_val} |
| Unique goal templates in train | {n_unique_train_tmpls} |
| Unique goal templates in val | {n_unique_val_tmpls} |
| Val templates also appearing in train | {n_shared} / {n_unique_val_tmpls} ({100 * n_shared // n_unique_val_tmpls}%) |
| Val rows labelled `template_seen` | {template_seen_count} / {n_val} ({100 * template_seen_count // n_val}%) |
| Val rows with ≥10 train examples sharing same template | {high_mem} / {n_val} ({100 * high_mem // n_val}%) |

**Mechanism:** D-Random masks ~20% of non-goal tokens uniformly at random. The model learns
P(masked token | context). When the validation trajectory uses a goal template already seen during
training, the model can predict the masked tokens by pattern-matching against memorized
template-to-token distributions — without understanding *why* those tokens appear.

D-Random `rb_const20` achieves train=0.219, val=0.278 — a gap of only **0.059**. This near-zero
generalization gap signals memorization: train and val are testing the same template patterns.

### Memorization Risk Tier Breakdown (Validation)

| Tier | Count | Definition |
|---|---|---|
| high (≥10 train examples with same template) | {mem_tier_counts.get('high', 0)} | Very likely memorized |
| medium (3–9 train examples) | {mem_tier_counts.get('medium', 0)} | Likely memorized |
| low (1–2 train examples) | {mem_tier_counts.get('low', 0)} | Possible memorization |
| zero_ood (no training examples with same template) | {mem_tier_counts.get('zero_ood', 0)} | Genuine OOD |

---

## 2. Is Memorization Driven by Trajectory Length?

**Answer: No.** Template leakage is nearly uniform across all trajectory length bins.

{render_table(length_rows, ["length_bin", "val_count", "template_seen_pct", "avg_template_train_count", "family_seen", "strong_ood", "high_mem_count"])}

`template_seen_pct` is near-100% in every length bin. The memorization is not concentrated in
short trajectories — it reflects the original dataset split, which assigned trajectories to
train/validation/test randomly without grouping by goal template.

**Implication for the "16k token" observation:** `train_llada_rb.py` drops trajectories exceeding
`max_len` rather than truncating (returns `None` at the length check). If some trajectories are
very long (approaching 16k tokens), they are excluded from training and evaluation alike. This
length-based dropout could create a selection bias toward shorter trajectories in later-stage
analysis, but it does not explain the memorization pattern — which exists uniformly across the
trajectories that ARE loaded.

---

## 3. Training Curves: D-Random vs D-Flex vs Causal
{log_sections}
### Aggregate Model Comparison

| Run | Objective | Train Loss | Val Loss | Gap (val−train) | Duration |
|---|---|---|---|---|---|
| rb_const20 | D-Random (const 20%) | 0.219 | 0.278 | +0.059 | 113 min |
| rb_curric | D-Random (curriculum) | 1.172 | 1.099 | −0.073 | 109 min |
| causal20 | Causal suffix (D-AR) | 4.488 | 4.104 | −0.384 | 105 min |
| llada_dflex_full | D-Flex (9 objectives) | 4.410 | 2.483 | −1.927 | 45 min |

{causal_variance_note}

**Why D-Flex val < train:** At evaluation time, 3 random batches are drawn using the same
objective mixture as training. Some batches get easy objectives (goal_conditioned_action, loss 1.56)
and some get hard ones (retrodiction, loss 12.1). With only 3 batches, this sampling noise makes
the checkpoint estimate unreliable. The fact that val < train likely reflects lucky sampling of
easier objectives during the three checkpoint evaluations, not that validation is genuinely easier.

**Why these numbers are not directly comparable across models:** D-Random and D-Flex use different
masking objectives. D-Random's val loss (0.278) is measuring "random token prediction on
template-seen data" while D-Flex's val loss (2.483) is measuring a mixture of 9 structured
objectives. Comparing them directly is like comparing perplexity on different vocabularies.

---

## 4. D-Flex Objective Analysis: What Is Being Learned?

{dflex_table}

**Key observations:**

- `retrodiction` (loss 12.1): Predict *earlier* trajectory tokens given only *later* context.
  Requires backward causal reasoning. Completely unsolvable by template memorization.
- `full_completion` (loss 9.2): Generate an entire trajectory from the goal alone. High structural
  demand — the model must know HOW the environment responds to sequences of actions.
- `inverse_dynamics` (loss 3.97): Given obs_t and obs_{{t+1}}, predict the action that caused the
  transition. This is the causal world-model objective: learn what actions have what effects.
- `goal_conditioned_action` (loss 1.56): Given the goal, predict which action blocks appear.
  This CAN be partially solved by template patterns (templates imply typical action sequences).

D-Flex's high average loss reflects that it is learning structurally harder tasks than D-Random.
A model trained on retrodiction and inverse_dynamics builds a world model, not a template lookup
table. **Higher D-Flex loss ≠ worse learning.**

---

## 5. Per-Family Coverage and Template Overlap

{render_table(family_rows, ["goal_family", "train", "val", "train_templates", "val_templates", "val_tmpl_in_train", "overlap_pct"])}

All 12 goal families are represented in both train and validation. `overlap_pct` shows the fraction
of each family's validation templates that were also seen in training. Near-100% overlap across all
families confirms the memorization is not limited to a specific task type — it is structural to
how the split was constructed.

---

## 6. What Would Stratified Sampling Reveal?

### Split Risk Distribution Under Each Protocol

{sim_table}

**Interpretation:**

- **Current split** — 98.6% `template_seen`. The model is tested on memorized template patterns.
  D-Random thrives here. A model that achieves val=0.278 on this split has not demonstrated
  generalization.

- **IID balanced** — Groups exact/near-duplicate trajectories before splitting, preventing
  byte-for-byte duplication from leaking. But goal *templates* can still cross the split boundary.
  Template overlap is partially reduced.

- **Grouped OOD** — No goal templates cross the train/val boundary (verified by
  `artifacts/benchmark_verification.json`: ood_goal_template_overlap = 0 across all pairs).
  Validation measures performance on goal templates the model has never seen.
  Expected outcome: D-Random val loss increases substantially (template memorization useless);
  D-Flex loss may remain more stable (it learned structural patterns, not templates).

### The Critical Experiment (Not Yet Run)

Train D-Random and D-Flex on the **same training portion of the grouped OOD split**, then evaluate
both on the same validation portion, using a **shared fixed evaluation objective** (e.g.,
`next_observation`). If D-Random's loss jumps while D-Flex's stays low, the memorization
hypothesis is confirmed. If both jump proportionally, the representations were equally
structure-dependent and template-independent.

Use `artifacts/split_grouped_ood.json` for trajectory_id assignment.

---

## 7. Is It In-Domain? Comparing D-Random vs D-Flex Domain Coverage

Both D-Random and D-Flex train and validate on **ScienceWorld** data only. The downstream
benchmarks of interest are **ALFWorld** and **WebShop** — both unseen environments.

D-Random's world model is: "which tokens follow which templates in ScienceWorld?" This is deeply
environment-specific. On ALFWorld or WebShop, none of the learned template associations transfer.

D-Flex's world model is: "what actions cause what observation transitions, how do trajectories
unfold backward in time, what fills the gap between two observed states?" These are structural
questions about *interactive environment trajectories* as a general class. They are more likely to
transfer to new environments.

This is the strongest argument for D-Flex: even if its ScienceWorld validation loss looks worse
on the current (memorization-friendly) split, its representations encode causal structure that
generalizes across environments. D-Random encodes ScienceWorld template distributions.

---

## 8. Impact of Each Dataset Component

### Training Signal Contribution by Objective Type

| Category | Objectives | D-Flex Weight | Can Memorization Solve It? |
|---|---|---|---|
| Causal generation | next_action, next_observation, future_from_past, full_completion | 55% | Partially (template-seen trajectories) |
| Goal-action alignment | goal_conditioned_action | 5% | Yes (template → action mapping) |
| Bidirectional causal | inverse_dynamics, retrodiction, intermediate_imputation, observation_denoising | 40% | No (requires world-model understanding) |

D-Flex allocates ~40% of training signal to objectives that template memorization cannot satisfy.
D-Random allocates 0% to such objectives.

### Dataset Length Component

| Bin | Train count | Val count | Avg actions | Primary risk |
|---|---|---|---|---|
| short (≤8 actions) | 587 | 81 | ≤8 | Template memorization (simple patterns) |
| medium (9–20 actions) | 458 | 46 | 9–20 | Template memorization (moderate complexity) |
| long (>20 actions) | 142 | 21 | >20 | Still template-seen; harder to memorize exactly |

Short trajectories dominate (50% of train), but memorization is not concentrated there — it is
uniform due to the template-level leakage.

---

## 9. Recommended Next Steps

1. **Run the grouped OOD comparison.** Use `split_grouped_ood.json` to retrain D-Random and D-Flex
   on the OOD-clean training split and evaluate on its validation split. Use `next_observation` as
   the shared evaluation objective. This is the definitive experiment.

2. **Implement `eval_per_trajectory.py`** to compute per-trajectory loss for existing checkpoints.
   Join with `artifacts/memorization_scores.csv` to verify that D-Random loss correlates with
   `template_train_count` (memorization tier) while D-Flex loss does not.

3. **Add `best_val_nextobs_loss` tracking to all future runs.** The current `train_llada_rb.py`
   evaluates with `sample_objective(progress, rng)` — a random objective. Replace with a fixed
   `next_observation` probe at each checkpoint for consistent comparison across all objective sets.

4. **Do not use aggregate val loss to compare D-Random vs D-Flex.** The losses are measured
   under different objective distributions and are not commensurable. Use a fixed shared probe.

5. **Treat `artifacts/split_grouped_ood.json` as the headline validation benchmark** going forward.
   See also `artifacts/split_iid_balanced.json` for the sanity-check benchmark.
"""
    return report
